version: '3'

services:
  postgres:
    image: postgres:latest
    volumes:
      - /data/ignite-cross-chain-bridge-backend/postgres/data:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '0.0.0.0:${DB_DOCKER_COMPOSE_PORT}:5432'
    restart: unless-stopped
  file-worker:
    build: .
    env_file: .env
    restart: unless-stopped
    ports:
      - 0.0.0.0:${DOCKER_COMPOSE_PORT}:80
    volumes:
      - /data/file-worker/logs:/usr/src/app/logs
